[package]
name = "poseidon_hasher"
version = "0.1.0"
edition = "2021"
default-run = "poseidon_hasher"

[dependencies]
byteorder = "1.5.0"
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }
